apiVersion: v1
kind: Service
metadata:
  name: rsvp
  namespace: default  
  labels:
    apps: rsvp
spec:
  type: NodePort
  ports:
  - name: tcp-31081-5000
    nodePort: 31081
    port: 5000
    protocol: TCP
  selector:
    app: rsvp
