apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: default  
  labels:
    app: rsvpdb
spec:
  type: ClusterIP
  ports:
  - port: 27017
    protocol: TCP
  selector:
    appdb: rsvpdb
